version: '2'
services:
  app:
    container_name: "${PREFIX_CONTAINER}app"
    hostname:       "${PREFIX_CONTAINER}app"
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - MONO_TOKENS=${MONO_TOKENS}
      - TELEGRAM_ADMINS=${TELEGRAM_ADMINS}
      - TELEGRAM_CHATS=${TELEGRAM_CHATS}
      - LOG_LEVEL=${LOG_LEVEL}
      - SCHEDULE_TIME=${SCHEDULE_TIME}
    ports:
      - ${APP_PORT}:8080
    logging:
      options:
        max-file: 5
        max-size: 15m
