on: [push, pull_request]

name: Test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.21.x
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.OS }}-go-${{ env.cache-name }}-
          ${{ runner.OS }}-go-
          ${{ runner.OS }}-

    - name: Verify dependencies
      run: go mod verify

    - name: Run Gosec
      uses: securego/gosec@master
      with:
        args: '-exclude=G104 ./...'

    - name: Run tests
      run: go test -race -vet=off ./...
